import type { Metadata } from "next";
import { ShieldCheck, Sparkles } from "lucide-react";
import { getAnalytics } from "@/lib/analytics";
import { getRoi } from "@/lib/roi";
import { formatInr, formatInrCompact } from "@/lib/format";
import { LogoMark, Wordmark } from "@/components/brand/logo";
import { PrintButton } from "@/components/roi/print-button";

export const metadata: Metadata = {
  title: "Care continuity & impact report — HealthcareOS"
};

/**
 * Board-ready artifact: monthly ROI proof + leakage audit in one document.
 * Lives outside the (app) shell so it renders & prints as a clean sheet.
 */
export default async function RoiReportPage() {
  const [roi, analytics] = await Promise.all([getRoi(), getAnalytics()]);
  const k = roi.kpis;
  const worklist = [...analytics.worklist].sort((a, b) => b.value - a.value).slice(0, 6);
  const wins = roi.ledger.filter((r) => r.stage === "converted" || r.stage === "observed").slice(0, 5);

  return (
    <div className="min-h-dvh bg-canvas px-4 py-8 print:bg-white print:p-0">
      <article className="mx-auto max-w-3xl">
        {/* Toolbar (screen only) */}
        <div className="mb-5 flex items-center justify-between print:hidden">
          <p className="text-sm text-ink-muted">Generated by HealthcareOS · share with ownership & finance</p>
          <PrintButton />
        </div>

        <div className="surface-card overflow-hidden print:rounded-none print:border-0 print:shadow-none">
          {/* Document header */}
          <header className="border-b border-line p-8 pb-6">
            <div className="flex items-start justify-between gap-4">
              <div className="flex items-center gap-3">
                <LogoMark size={40} />
                <div>
                  <Wordmark className="block text-lg" />
                  <p className="text-xs text-ink-muted">Care continuity & impact report</p>
                </div>
              </div>
              <span className="rounded-md border border-line px-2 py-1 text-[10px] font-semibold uppercase tracking-wider text-ink-muted">
                Confidential
              </span>
            </div>
            <div className="mt-6 grid grid-cols-2 gap-x-6 gap-y-1.5 text-sm sm:grid-cols-4">
              <Meta label="Organisation" value={roi.tenant} wide />
              <Meta label="Branch" value={roi.branch} wide />
              <Meta label="Period" value={roi.period} wide />
              <Meta label="Prepared for" value={roi.preparedFor} wide />
            </div>
          </header>

          {/* Executive summary */}
          <section className="border-b border-line p-8 py-6">
            <SectionHeading n={1} title="Executive summary" />
            <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-3">
              <BigNumber label="Care continuity maintained" value={formatInrCompact(k.recovered)} note={k.recoveredDelta} tone="good" />
              <BigNumber label="Care continuity still at risk" value={formatInrCompact(k.outstandingLeakage)} note={`${analytics.worklist.length}+ open items, owned & actionable`} tone="risk" />
              <BigNumber label="Projected next quarter" value={formatInrCompact(k.projectedNextQuarter)} note="At trailing continuity rate" tone="brand" />
            </div>
            <p className="mt-4 text-sm leading-relaxed text-ink-soft">
              In this period, {roi.branch} kept <strong className="text-ink">{formatInr(k.recovered)}</strong> of care in motion —
              value that would otherwise have been lost as patients fell out of care through missed follow-ups, unbooked advised procedures,
              pending diagnostics and no-shows. {k.aiDrivenShare}% of this continuity was initiated by DatacentrIQ intelligence and approved by
              staff; {k.attributionRate}% of entries carry a complete, auditable evidence chain.
            </p>
          </section>

          {/* Leakage audit */}
          <section className="border-b border-line p-8 py-6">
            <SectionHeading n={2} title="Care gaps audit — where patients fall out of care" />
            <table className="mt-4 w-full text-sm">
              <thead>
                <tr className="border-b border-line text-left text-[10px] uppercase tracking-wider text-ink-muted">
                  <th className="pb-2 font-semibold">Category</th>
                  <th className="pb-2 text-right font-semibold">At risk</th>
                  <th className="pb-2 text-right font-semibold">Kept in care</th>
                  <th className="pb-2 text-right font-semibold">Open items</th>
                  <th className="pb-2 text-right font-semibold">Continuity rate</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-line">
                {roi.byCategory.map((category) => {
                  const rate = Math.round((category.recovered / (category.recovered + category.atRisk)) * 100);
                  return (
                    <tr key={category.label}>
                      <td className="py-2 text-ink">{category.label}</td>
                      <td className="py-2 text-right tabular-nums text-[var(--color-critical)]">{formatInrCompact(category.atRisk)}</td>
                      <td className="py-2 text-right tabular-nums text-[var(--color-good)]">{formatInrCompact(category.recovered)}</td>
                      <td className="py-2 text-right tabular-nums text-ink-soft">{category.items}</td>
                      <td className="py-2 text-right font-semibold tabular-nums text-ink">{rate}%</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>

            <p className="mb-2 mt-6 text-[10px] font-semibold uppercase tracking-wider text-ink-faint">
              Highest-value open items (sample)
            </p>
            <ul className="space-y-1.5">
              {worklist.map((item) => (
                <li key={item.id} className="flex items-baseline justify-between gap-3 text-sm">
                  <span className="min-w-0 truncate text-ink">
                    {item.patient}
                    <span className="text-ink-muted"> — {item.category.toLowerCase()}, open {item.ageDays}d, owner: {item.owner}</span>
                  </span>
                  <span className="shrink-0 font-semibold tabular-nums text-ink">{formatInrCompact(item.value)}</span>
                </li>
              ))}
            </ul>
          </section>

          {/* Recovered wins */}
          <section className="border-b border-line p-8 py-6">
            <SectionHeading n={3} title="Patients brought back into care — proof of work" />
            <ul className="mt-4 space-y-3">
              {wins.map((win) => (
                <li key={win.id} className="flex items-start justify-between gap-4 text-sm">
                  <div className="min-w-0">
                    <p className="font-medium text-ink">
                      {win.patient} <span className="font-normal text-ink-muted">· {win.maskedPhone}</span>
                    </p>
                    <p className="mt-0.5 text-ink-soft">{win.action}</p>
                    <p className="mt-0.5 font-mono text-[10px] text-ink-faint">
                      Evidence: {win.evidence.join(" → ")} · {win.actor}
                    </p>
                  </div>
                  <span className="shrink-0 font-semibold tabular-nums text-[var(--color-good)]">{formatInrCompact(win.value)}</span>
                </li>
              ))}
            </ul>
            <p className="mt-4 flex items-center gap-1.5 text-xs text-ink-muted">
              <Sparkles className="size-3.5 text-brand-500" />
              {k.aiDrivenShare}% of this care continuity was AI-initiated; every AI action was approved by named staff.
            </p>
          </section>

          {/* Methodology */}
          <section className="p-8 py-6">
            <SectionHeading n={4} title="Methodology & assumptions" />
            <ol className="mt-3 list-decimal space-y-1.5 pl-5 text-xs leading-relaxed text-ink-soft">
              {roi.methodology.map((line) => (
                <li key={line}>{line}</li>
              ))}
            </ol>
            <p className="mt-6 flex items-center gap-1.5 border-t border-line pt-4 text-[10px] text-ink-faint">
              <ShieldCheck className="size-3.5" />
              Generated by HealthcareOS · DatacentrIQ-powered · All underlying records auditable in-platform · {roi.period}
            </p>
          </section>
        </div>
      </article>
    </div>
  );
}

function Meta({ label, value, wide }: { label: string; value: string; wide?: boolean }) {
  return (
    <div className={wide ? "col-span-2 sm:col-span-1" : undefined}>
      <p className="text-[10px] font-semibold uppercase tracking-wider text-ink-faint">{label}</p>
      <p className="mt-0.5 text-sm font-medium text-ink">{value}</p>
    </div>
  );
}

function SectionHeading({ n, title }: { n: number; title: string }) {
  return (
    <h2 className="flex items-center gap-2.5 text-base font-semibold tracking-tight text-ink">
      <span className="flex size-6 items-center justify-center rounded-md bg-brand-50 text-xs font-semibold text-brand-700">{n}</span>
      {title}
    </h2>
  );
}

function BigNumber({ label, value, note, tone }: { label: string; value: string; note: string; tone: "good" | "risk" | "brand" }) {
  const toneClass = {
    good: "text-[var(--color-good)]",
    risk: "text-[var(--color-critical)]",
    brand: "text-brand-600"
  }[tone];
  return (
    <div className="rounded-xl border border-line p-4">
      <p className="text-[10px] font-semibold uppercase tracking-wider text-ink-muted">{label}</p>
      <p className={`mt-1 text-2xl font-semibold tabular-nums tracking-tight ${toneClass}`}>{value}</p>
      <p className="mt-1 text-xs text-ink-muted">{note}</p>
    </div>
  );
}
